version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  file:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - /local/entertainment:/files
    environment:
      - NODE_ENV=prod
    labels:
      - traefik.backend=file
      - traefik.frontend.rule=Host:file.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=8100
    networks:
      - internal
      - proxy
